### PR TITLE
adding the link to VS code Snippets

### PR DESCRIPTION
**Pull request by HombreGeek**
It's a resource to those we use Visual Studio Code as IDE.
Consider updating this part with the link

### CODE REVIEW

**Comment by janschoenherr** [comment]
Thanks, personally I am not using Visual Studio Code. It would be great if someone could test and provide feedback!

**Comment by dons20** [comment]
Bump, I didn't realize this had been brought up before. I would do the testing but since I'm the one who made it I'm not sure if I'm the ideal person 😅. Can probably bring it up in the gitter group for some more feedback.

**Comment by mohsenkhanpour** [comment]
I use this extension a lot. It has auto-complete for uk-* tags, very convenient.

**Comment by janschoenherr** [comment]
This has been added. Thanks!

**Pull request closed without merging**
