### PR TITLE
Add Toggleable Filters Section on Filter component page ?

### PR DESCRIPTION
**Pull request by FrancoisCapon**
I'm looking to use Filter component to build toggleable filters on posts'tags of a blog.

I found this plugin : https://www.beaverplugins.com/examples/uikit-dynamic-groups-filter/

I study the code and the UIkit Documentation and eureka! No javascript needed. Toggle component do the trick. So no plugin needed, just use the two Filter and Toggle components.

### CODE REVIEW

**Comment by sharpchris** [comment]
I found this helpful, thank you!

**Comment by 7fases** [comment]
I was looking for a solution like this!

Would there be a way to create a button to "clear the filters" applied?? Something like
` <li class = "uk-active" uk-filter-control target: .filtro-ps4> <a href="#"> All </a> </li>`

And that shows all items without filters

**Comment by FrancoisCapon** [comment]
Good idea, a filter "all" can be very useful.

I added your idea to my code, it needs some  Javascript to have a consistent between filters "meta" and the "all" filter:
* https://gist.github.com/FrancoisCapon/b88a3b8613e7b32abd923efc6160df7f

@sharpchris and @7fases thanks for the emoji!

**Comment by 7fases** [comment]
It was very good!

I think these are the perfect filters for any project.

I was thinking of placing the options in a way that looks better on the screen, I thought of the ["Off-canvas"  function](https://getuikit.com/docs/offcanvas) to open more comfortably even on smartphone screens (pulling a slide screen), but I think it breaks the code by some reason. I also don't know if it is the best option for a project with several types of filters that break the mobile screen ^^.

**Comment by 7fases** [comment]
It was very good! I forgot to thank you, I'm setting up a game [filter on a website](https://www.pocaodemana.com/2020/06/mega-lista-de-games-multiplayer.html) (for fun and be useful) and this will help me a lot!

I think these are the perfect filters for any project.

Thanks

**Comment by 7fases** [comment]
Is it possible to apply two targets in the toggle function? I'm  trying to create a line to show the filters that are currently applied, I thought about using the toggle function for that too, but something is wrong ^^.

```
uk-toggle = "target: .filtro-xone-platforms; target: .another-item"

 <p class="another-item" hidden>active filter</p>
```

**Comment by FrancoisCapon** [comment]
Yes, here is a  example:

```html
<div>
    <button class="uk-button uk-button-default" type="button"
                   uk-toggle="target: #toggle-one, #toggle-two">Toggle
    </button>
    <p id="toggle-one">What's up one?</p>
    <p id="toggle-two">What's up two?</p>
</div>
```

I think that [target](https://getuikit.com/docs/toggle#component-options) works as the _selectors_ parameter of [document.querySelectorAll(selectors)](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll). 

P.S. Your site looks great but why so much ads?

**Comment by 7fases** [comment]
@FrancoisCapon Thanks again man! it was so simple haha, it was so simple haha, i'm not from that area, i'm just venturing to create this list, i believe that this filter system can be very nice for this function

I'm still creating the page, I'm not sure which ads I'll leave at the end, anyway in Brazil the value per ad is really low haha

**Pull request closed without merging**
